//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novoe_prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Терминал.
    /// </summary>
    // *** Start programmer edit section *** (Терминал CustomAttributes)

    // *** End programmer edit section *** (Терминал CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Терминал", new string[] {
            "НомерТер as \'ID терминала\'"})]
    [View("Терминал", new string[] {
            "НомерТер as \'ID терминала\'"})]
    public class Терминал : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерТер;
        
        // *** Start programmer edit section *** (Терминал CustomMembers)

        // *** End programmer edit section *** (Терминал CustomMembers)

        
        /// <summary>
        /// НомерТер.
        /// </summary>
        // *** Start programmer edit section *** (Терминал.НомерТер CustomAttributes)

        // *** End programmer edit section *** (Терминал.НомерТер CustomAttributes)
        public virtual int НомерТер
        {
            get
            {
                // *** Start programmer edit section *** (Терминал.НомерТер Get start)

                // *** End programmer edit section *** (Терминал.НомерТер Get start)
                int result = this.fНомерТер;
                // *** Start programmer edit section *** (Терминал.НомерТер Get end)

                // *** End programmer edit section *** (Терминал.НомерТер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Терминал.НомерТер Set start)

                // *** End programmer edit section *** (Терминал.НомерТер Set start)
                this.fНомерТер = value;
                // *** Start programmer edit section *** (Терминал.НомерТер Set end)

                // *** End programmer edit section *** (Терминал.НомерТер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Терминал" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Терминал
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Терминал", typeof(IIS.Novoe_prilozhenie.Терминал));
                }
            }
            
            /// <summary>
            /// "Терминал" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Терминал2
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Терминал", typeof(IIS.Novoe_prilozhenie.Терминал));
                }
            }
        }
    }
}
