//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novoe_prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Шлагбаум.
    /// </summary>
    // *** Start programmer edit section *** (Шлагбаум CustomAttributes)

    // *** End programmer edit section *** (Шлагбаум CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Шлагбаум", new string[] {
            "НомерШлаг as \'ID шлагбаума\'",
            "Положение as \'Положение шлагбаума\'"})]
    [View("Шлагбаум", new string[] {
            "НомерШлаг as \'ID шлагбаума\'",
            "Положение as \'Положение шлагбаума\'"})]
    public class Шлагбаум : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерШлаг;
        
        private IIS.Novoe_prilozhenie.Положения fПоложение;
        
        // *** Start programmer edit section *** (Шлагбаум CustomMembers)

        // *** End programmer edit section *** (Шлагбаум CustomMembers)

        
        /// <summary>
        /// НомерШлаг.
        /// </summary>
        // *** Start programmer edit section *** (Шлагбаум.НомерШлаг CustomAttributes)

        // *** End programmer edit section *** (Шлагбаум.НомерШлаг CustomAttributes)
        public virtual int НомерШлаг
        {
            get
            {
                // *** Start programmer edit section *** (Шлагбаум.НомерШлаг Get start)

                // *** End programmer edit section *** (Шлагбаум.НомерШлаг Get start)
                int result = this.fНомерШлаг;
                // *** Start programmer edit section *** (Шлагбаум.НомерШлаг Get end)

                // *** End programmer edit section *** (Шлагбаум.НомерШлаг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Шлагбаум.НомерШлаг Set start)

                // *** End programmer edit section *** (Шлагбаум.НомерШлаг Set start)
                this.fНомерШлаг = value;
                // *** Start programmer edit section *** (Шлагбаум.НомерШлаг Set end)

                // *** End programmer edit section *** (Шлагбаум.НомерШлаг Set end)
            }
        }
        
        /// <summary>
        /// Положение.
        /// </summary>
        // *** Start programmer edit section *** (Шлагбаум.Положение CustomAttributes)

        // *** End programmer edit section *** (Шлагбаум.Положение CustomAttributes)
        public virtual IIS.Novoe_prilozhenie.Положения Положение
        {
            get
            {
                // *** Start programmer edit section *** (Шлагбаум.Положение Get start)

                // *** End programmer edit section *** (Шлагбаум.Положение Get start)
                IIS.Novoe_prilozhenie.Положения result = this.fПоложение;
                // *** Start programmer edit section *** (Шлагбаум.Положение Get end)

                // *** End programmer edit section *** (Шлагбаум.Положение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Шлагбаум.Положение Set start)

                // *** End programmer edit section *** (Шлагбаум.Положение Set start)
                this.fПоложение = value;
                // *** Start programmer edit section *** (Шлагбаум.Положение Set end)

                // *** End programmer edit section *** (Шлагбаум.Положение Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Шлагбаум" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Шлагбаум
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Шлагбаум", typeof(IIS.Novoe_prilozhenie.Шлагбаум));
                }
            }
            
            /// <summary>
            /// "Шлагбаум" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Шлагбаум2
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Шлагбаум", typeof(IIS.Novoe_prilozhenie.Шлагбаум));
                }
            }
        }
    }
}
